### ISSUE TITLE
Watchface not showing - "IQ" instead

### ISSUE THREAD

**Issue by kackburt** [lynchdean/DeansSimpleWatchFace#5]
When not wearing the watch on the wrist for a longer period of time (not tested thoroughly enough to say when exactly - mostly minutes), the watch face doesn't show anymore. Instead the user is greeted with a black screen and the text/logo "IQ" (Garmin Connect IQ I suppose).
When putting the watch back on the wrist and reloading the watchface (f.e. by going up/down to glances and back to the watchface), it shows the watchface again.

- Device: Garmin Forerunner 965
- Garmin OS Version: 19.18
- Dean's Simple Watch Face Version: 1.2.6

**Comment by lynchdean** [comment]
This is a known issue to me which I have improved on but failed to eliminate with some quick fixes. The next update I push I will only proceed if I'm confident the issue has been resolved.

I have noticed this too in two different scenarios:
1) Turning on the watch when it is not on my wrist.
2) After completing a workout (Run). 

This makes me think the issue is maybe HR related but I have yet to successfully confirm this. Unfortunately this is not something I can test on the simulator, so I have to upload a test build and test on my own watch over a few days and repeat each time I make any changes.

**Comment by lynchdean** [comment]
Fix implemented and initial outlook is good for both fixing this issue alongside the colour changing issue. Will test for approx 2 days on my personal device first before uploading build to Garmin.

**Comment by lynchdean** [comment]
Two days testing on my personal device with no IQ error. I'm going to upload the build to Garmin tomorrow (I want to just try another couple of real activities just to confirm) if that is still the case by then.

**Comment by lynchdean** [comment]
Apologies for the long wait. That update didn't fix things and truthfully due to the lack of documentation available I was out of ideas. Fortunately I began working on another watch face for a different project and in the process of that I discovered a best practice that I was not applying to this project, which will eliminate null errors causing a crash. I've pushed a new update 1.3.0 and I'm way more confident that this fixes the issue.
